name: CI

env:
  TOGGLE_STATUS: on

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:
  
jobs:

  build:  
    runs-on: ubuntu-latest   
    steps:
      - name: example
        run: |
          echo "This step will only run if the toggle switch is on"
        if: env.TOGGLE_STATUS == 'off'

